"""Windows HTTP bridge for TraeWork's native ``ai-agent`` AHA service.

TraeWork does not speak a four-byte TCP protocol here.  Its bundled
``@aha-kit/ipc`` client uses ZeroMQ DEALER/ROUTER envelopes and the bundled
``@aha-kit/rpc`` client sends JSON-RPC messages inside those envelopes.  This
helper implements that protocol directly when ``pyzmq`` is installed.  The
old length-prefixed TCP probe is retained only behind the explicit
``TRAEWORK_NATIVE_AHA_TRANSPORT=tcp-legacy`` setting for diagnostics.

The native DLLs stay in the local TraeWork installation; this process owns
the AHA client and the HTTP/SSE adapter.
"""

from __future__ import annotations

import argparse
import asyncio
import json
import os
import socket
import struct
import sys
import tempfile
import uuid
from pathlib import Path
from typing import Any, AsyncIterator, Mapping, Optional

from fastapi import FastAPI, HTTPException, Request
from fastapi.responses import StreamingResponse
import uvicorn

PROJECT_ROOT = Path(__file__).resolve().parents[1]
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from src.traework_native_bridge import AhaFrameDecoder, NativeBridgeProtocolError


app = FastAPI(title="TraeWork Native Bridge")

IPC_VERSION = 1
PACKET_USER = "user"
PACKET_CONTROL = "control"
PING = "__C_PING__"
PONG = "__C_PONG__"
SERVER_SHUTDOWN = "__C_SERVER_SHUTDOWN__"
CONNECTION_REJECT = "__CONNECTION_REJECT__"
STREAM_PREFIX = "rpc.stream."
STREAM_CANCEL_PREFIX = "rpc.stream.cancel."


def _env_int(name: str, default: int) -> int:
    try:
        return int(os.environ.get(name, str(default)))
    except (TypeError, ValueError):
        return default


def _env_float(name: str, default: float, minimum: float = 0.0) -> float:
    try:
        value = float(os.environ.get(name, str(default)))
    except (TypeError, ValueError):
        value = default
    return max(minimum, value)


def _aha_transport() -> str:
    value = os.environ.get("TRAEWORK_NATIVE_AHA_TRANSPORT", "zmq").strip().lower()
    if value in {"zmq", "zeromq", "aha"}:
        return "zmq"
    if value in {"tcp-legacy", "legacy", "length-prefixed"}:
        return "tcp-legacy"
    raise RuntimeError("unsupported TRAEWORK_NATIVE_AHA_TRANSPORT; use zmq or tcp-legacy")


def _aha_host() -> str:
    return os.environ.get("TRAEWORK_NATIVE_AHA_HOST", "127.0.0.1").strip() or "127.0.0.1"


def _aha_port() -> int:
    return max(1, _env_int("TRAEWORK_NATIVE_AHA_PORT", 40005))


def _aha_byteorder() -> str:
    value = os.environ.get("TRAEWORK_NATIVE_AHA_BYTEORDER", ">").strip()
    return value if value in {">", "<"} else ">"


def _aha_server_name() -> str:
    return os.environ.get("TRAEWORK_NATIVE_AHA_SERVER_NAME", "ai-agent").strip() or "ai-agent"


def _aha_address() -> str:
    """Return the address generated by @aha-kit/ipc's generateIpcAddress."""

    explicit = os.environ.get("TRAEWORK_NATIVE_AHA_ADDRESS", "").strip()
    if explicit:
        return explicit
    runtime_dir = os.environ.get("TRAEWORK_NATIVE_AHA_RUNTIME_DIR", "").strip()
    root = Path(runtime_dir).expanduser() / "aha" if runtime_dir else Path(tempfile.gettempdir()) / "aha"
    safe_name = "".join(ch if (ch.isalnum() or ch in "._-") else "_" for ch in _aha_server_name())
    return "ipc://" + str(root / f"{safe_name}.sock")


def _connect_timeout() -> float:
    return _env_float("TRAEWORK_NATIVE_AHA_CONNECT_TIMEOUT", 5.0, 0.1)


def _rpc_timeout() -> float:
    return _env_float("TRAEWORK_NATIVE_AHA_RPC_TIMEOUT", 30.0, 0.1)


def _bridge_token() -> str:
    return os.environ.get("TRAEWORK_NATIVE_BRIDGE_TOKEN", "").strip()


def _frame(packet: Mapping[str, Any]) -> bytes:
    """Encode the explicitly opt-in legacy length-prefixed probe frame."""

    payload = json.dumps(packet, ensure_ascii=False, separators=(",", ":")).encode("utf-8")
    return struct.pack(f"{_aha_byteorder()}I", len(payload)) + payload


def _sse(frame: Any) -> str:
    if isinstance(frame, Mapping):
        data: Any = frame
        if isinstance(frame.get("data"), Mapping) and frame.get("code") in (None, 0):
            data = frame["data"]
        if not isinstance(data, Mapping):
            data = {"value": data}
        event = str(data.get("event") or frame.get("event") or data.get("type") or "message")
        if event.lower() in {"done", "complete", "completed"}:
            event = "done"
        return f"event: {event}\ndata: {json.dumps(dict(data), ensure_ascii=False, separators=(',', ':'))}\n\n"
    return f"event: message\ndata: {json.dumps({'value': frame}, ensure_ascii=False)}\n\n"


def _packet(server_id: str, packet_type: str, payload: Any) -> dict[str, Any]:
    return {"version": IPC_VERSION, "id": server_id, "packet_type": packet_type, "payload": payload}


def _json_rpc_request(request_id: str, method: str, *params: Any) -> dict[str, Any]:
    message: dict[str, Any] = {"jsonrpc": "2.0", "method": method, "id": request_id}
    if params:
        message["params"] = [None if p is None else p for p in params]
    return message


def _json_rpc_notification(method: str, *params: Any, meta: Optional[Mapping[str, Any]] = None) -> dict[str, Any]:
    message: dict[str, Any] = {"jsonrpc": "2.0", "method": method}
    if params:
        message["params"] = [None if p is None else p for p in params]
    if meta is not None:
        message["meta"] = dict(meta)
    return message


class AhaZmqClient:
    """Minimal @aha-kit/ipc + @aha-kit/rpc compatible client."""

    def __init__(self, *, address: str, timeout: float):
        self.address = address
        self.timeout = timeout
        self.context = None
        self.socket = None
        self.routing_id = str(uuid.uuid4())
        self.server_id = ""
        self.request_id = 0

    async def __aenter__(self) -> "AhaZmqClient":
        try:
            import zmq  # type: ignore
            import zmq.asyncio  # type: ignore
        except ImportError as exc:
            raise RuntimeError(
                "TraeWork native AHA transport requires pyzmq; install pyzmq "
                "or set TRAEWORK_NATIVE_AHA_TRANSPORT=tcp-legacy only for diagnostics"
            ) from exc
        self.context = zmq.asyncio.Context.instance()
        self.socket = self.context.socket(zmq.DEALER)
        self.socket.setsockopt(zmq.IDENTITY, self.routing_id.encode("utf-8"))
        for option, value in (
            (getattr(zmq, "HEARTBEAT_IVL", None), 1000),
            (getattr(zmq, "HEARTBEAT_TTL", None), 3000),
            (getattr(zmq, "HEARTBEAT_TIMEOUT", None), 3000),
        ):
            if option is not None:
                try:
                    self.socket.setsockopt(option, value)
                except Exception:
                    pass
        self.socket.connect(self.address)
        await self._send_packet(_packet("", PACKET_CONTROL, PING))
        await self._wait_for_pong()
        return self

    async def __aexit__(self, *_args: object) -> None:
        if self.socket is not None:
            self.socket.close(linger=0)
            self.socket = None

    async def _send_packet(self, packet: Mapping[str, Any]) -> None:
        if self.socket is None:
            raise RuntimeError("AHA socket is not connected")
        await self.socket.send_string(json.dumps(packet, ensure_ascii=False, separators=(",", ":")))

    async def _recv_packet(self) -> dict[str, Any]:
        if self.socket is None:
            raise RuntimeError("AHA socket is not connected")
        while True:
            try:
                raw = await asyncio.wait_for(self.socket.recv(), timeout=self.timeout)
            except asyncio.TimeoutError as exc:
                raise RuntimeError("AHA IPC response timeout") from exc
            if isinstance(raw, (list, tuple)):
                raw = raw[-1]
            try:
                decoded = json.loads(bytes(raw).decode("utf-8"))
            except (UnicodeDecodeError, json.JSONDecodeError) as exc:
                raise RuntimeError("AHA IPC returned invalid JSON envelope") from exc
            if not isinstance(decoded, dict) or decoded.get("version") != IPC_VERSION:
                raise RuntimeError("AHA IPC returned an invalid versioned packet")
            # @aha-kit/ipc's liveness manager answers control pings while the
            # RPC layer is waiting for a response. Without this branch the
            # native server declares a long-running model stream dead after
            # its three-second liveness timeout.
            if decoded.get("packet_type") == PACKET_CONTROL and decoded.get("payload") == PING:
                target_id = str(self.server_id or decoded.get("id") or "")
                await self._send_packet(_packet(target_id, PACKET_CONTROL, PONG))
                if not self.server_id and target_id:
                    self.server_id = target_id
                continue
            return decoded

    async def _wait_for_pong(self) -> None:
        deadline = asyncio.get_running_loop().time() + _connect_timeout()
        while True:
            try:
                envelope = await asyncio.wait_for(self._recv_packet(), timeout=max(0.1, deadline - asyncio.get_running_loop().time()))
            except asyncio.TimeoutError as exc:
                raise RuntimeError("AHA IPC liveness handshake timed out") from exc
            if envelope.get("packet_type") != PACKET_CONTROL:
                continue
            payload = envelope.get("payload")
            if payload == PONG:
                self.server_id = str(envelope.get("id") or "")
                if not self.server_id:
                    raise RuntimeError("AHA IPC pong did not identify the server")
                return
            if payload in {SERVER_SHUTDOWN, CONNECTION_REJECT}:
                raise RuntimeError(f"AHA IPC rejected connection: {payload}")

    async def _send_rpc(self, method: str, *params: Any) -> str:
        request_id = str(self.request_id)
        self.request_id += 1
        message = _json_rpc_request(request_id, method, *params)
        payload = json.dumps(message, ensure_ascii=False, separators=(",", ":"))
        await self._send_packet(_packet(self.server_id, PACKET_USER, payload))
        while True:
            envelope = await self._recv_packet()
            if envelope.get("packet_type") != PACKET_USER:
                continue
            raw = envelope.get("payload")
            if not isinstance(raw, str):
                continue
            try:
                response = json.loads(raw)
            except json.JSONDecodeError:
                continue
            if str(response.get("id")) != request_id:
                continue
            if response.get("error"):
                error = response["error"]
                raise RuntimeError(str(error.get("message") or "AHA RPC request failed"))
            result = response.get("result")
            if not isinstance(result, Mapping) or not result.get("streamId"):
                raise RuntimeError("AHA RPC response did not include streamId")
            return str(result["streamId"])

    async def stream(self, packet: Mapping[str, Any]) -> AsyncIterator[Any]:
        stream_id = await self._send_rpc("request_stream", dict(packet))
        method = f"{STREAM_PREFIX}{stream_id}"
        done = False
        try:
            while True:
                envelope = await self._recv_packet()
                if envelope.get("packet_type") != PACKET_USER:
                    continue
                raw = envelope.get("payload")
                if not isinstance(raw, str):
                    continue
                try:
                    message = json.loads(raw)
                except json.JSONDecodeError:
                    continue
                if message.get("method") != method:
                    continue
                meta = message.get("meta") or {}
                params = message.get("params")
                params_obj = params[0] if isinstance(params, list) and params else params
                if not isinstance(meta, Mapping) or not meta.get("stream") or str(meta.get("streamId")) != stream_id:
                    continue
                if isinstance(params_obj, Mapping) and params_obj.get("error"):
                    error = params_obj["error"]
                    raise RuntimeError(str(error.get("message") or "AHA stream failed"))
                if meta.get("done"):
                    done = True
                    return
                if isinstance(params_obj, Mapping) and "data" in params_obj:
                    yield params_obj["data"]
        finally:
            if not done:
                try:
                    cancel = _json_rpc_notification(
                        f"{STREAM_CANCEL_PREFIX}{stream_id}",
                        {"streamId": stream_id, "reason": "http_client_closed"},
                    )
                    await self._send_packet(_packet(self.server_id, PACKET_USER, json.dumps(cancel, separators=(",", ":"))))
                except Exception:
                    pass


async def _stream_aha_zmq(packet: Mapping[str, Any]) -> AsyncIterator[str]:
    async with AhaZmqClient(address=_aha_address(), timeout=_rpc_timeout()) as client:
        async for chunk in client.stream(packet):
            yield _sse(chunk)


async def _stream_aha_tcp_legacy(packet: Mapping[str, Any]) -> AsyncIterator[str]:
    """Old probe transport, intentionally opt-in and never used by default."""

    loop = asyncio.get_running_loop()
    sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    sock.settimeout(_connect_timeout())
    try:
        await loop.run_in_executor(None, sock.connect, (_aha_host(), _aha_port()))
        await loop.run_in_executor(None, sock.sendall, _frame(packet))
        decoder = AhaFrameDecoder(byteorder=_aha_byteorder())
        sock.settimeout(None)
        while True:
            chunk = await loop.run_in_executor(None, sock.recv, 64 * 1024)
            if not chunk:
                decoder.finish()
                break
            for decoded in decoder.feed(chunk):
                yield _sse(decoded)
                data = decoded.get("data")
                event = str(decoded.get("event") or (data.get("event") if isinstance(data, Mapping) else "")).lower()
                if event in {"done", "complete", "completed"}:
                    return
    except (OSError, NativeBridgeProtocolError) as exc:
        raise RuntimeError("legacy AHA TCP request failed") from exc
    finally:
        try:
            sock.close()
        except OSError:
            pass


async def _stream_aha(packet: Mapping[str, Any]) -> AsyncIterator[str]:
    if _aha_transport() == "tcp-legacy":
        async for item in _stream_aha_tcp_legacy(packet):
            yield item
        return
    async for item in _stream_aha_zmq(packet):
        yield item


@app.get("/healthz")
async def healthz():
    return {
        "status": "ok",
        "service": "traework-native-helper",
        "transport": _aha_transport(),
        "aha_address": _aha_address(),
        "aha_host": _aha_host(),
        "aha_port": _aha_port(),
        "aha_server_name": _aha_server_name(),
    }


@app.post("/v1/traework/request_stream")
async def request_stream(request: Request):
    expected_token = _bridge_token()
    if expected_token and request.headers.get("x-trae-native-bridge-token", "") != expected_token:
        raise HTTPException(status_code=401, detail="invalid bridge token")
    try:
        packet = await request.json()
    except Exception as exc:
        raise HTTPException(status_code=400, detail="invalid JSON packet") from exc
    if not isinstance(packet, dict):
        raise HTTPException(status_code=400, detail="packet must be an object")
    packet_type = str(packet.get("packet_type") or "")
    if packet_type not in {"request", "request_stream", "request_lite", "request_stream_lite"}:
        raise HTTPException(status_code=400, detail="unsupported packet_type")

    async def body():
        try:
            async for item in _stream_aha(packet):
                if await request.is_disconnected():
                    return
                yield item
        except RuntimeError as exc:
            yield "event: error\ndata: " + json.dumps({"message": str(exc), "type": "api_error"}, ensure_ascii=False) + "\n\n"

    return StreamingResponse(body(), media_type="text/event-stream", headers={"Cache-Control": "no-cache", "Connection": "keep-alive"})


def main() -> None:
    if sys.platform != "win32" and os.environ.get("TRAEWORK_NATIVE_ALLOW_NON_WINDOWS", "").lower() not in {"1", "true", "yes", "on"}:
        raise SystemExit("TraeWork native helper is Windows-only; set TRAEWORK_NATIVE_ALLOW_NON_WINDOWS=true for protocol tests")
    parser = argparse.ArgumentParser()
    parser.add_argument("--host", default=os.environ.get("TRAEWORK_NATIVE_BRIDGE_HOST", "127.0.0.1"))
    parser.add_argument("--port", type=int, default=_env_int("TRAEWORK_NATIVE_BRIDGE_PORT", 40006))
    args = parser.parse_args()
    uvicorn.run(app, host=args.host, port=args.port, log_level=os.environ.get("LOG_LEVEL", "warning").lower())


if __name__ == "__main__":
    main()
